### ISSUE TITLE
Volume mapping for Artemis service in docker-compose

### ISSUE THREAD

**Issue by aspirio187** [openartcoded/app-docker#5]
# Description

When trying to map `/var/lib/artemis-instance/data` to route `./data/artemis` an error is produced by **Artemis**

```logs
artemis_1        | 2022-06-22 13:17:31,988 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101000: Starting ActiveMQ Artemis Server
artemis_1        | 2022-06-22 13:17:32,555 WARN  [org.apache.activemq.artemis.core.server] AMQ222141: Node Manager can not open file /var/lib/artemis-instance/data/journal/server.lock: java.io.IOException: No such file or directory
artemis_1        |      at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method) [java.base:]
artemis_1        |      at java.base/java.io.File.createNewFile(Unknown Source) [java.base:]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.FileBasedNodeManager.setUpServerLockFile(FileBasedNodeManager.java:146) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.FileLockNodeManager.setUpServerLockFile(FileLockNodeManager.java:108) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.FileLockNodeManager.start(FileLockNodeManager.java:99) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.internalStart(ActiveMQServerImpl.java:644) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.start(ActiveMQServerImpl.java:571) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.integration.FileBroker.start(FileBroker.java:64) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:127) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:160) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:108) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:135) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [java.base:]
artemis_1        |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [java.base:]
artemis_1        |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [java.base:]
artemis_1        |      at java.base/java.lang.reflect.Method.invoke(Unknown Source) [java.base:]
artemis_1        |      at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:134) [artemis-boot.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:50) [artemis-boot.jar:2.22.0]
artemis_1        | 
artemis_1        | 2022-06-22 13:17:32,560 ERROR [org.apache.activemq.artemis.core.server] AMQ224097: Failed to start server: java.io.IOException: No such file or directory
artemis_1        |      at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method) [java.base:]
artemis_1        |      at java.base/java.io.File.createNewFile(Unknown Source) [java.base:]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.FileBasedNodeManager.setUpServerLockFile(FileBasedNodeManager.java:146) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.FileLockNodeManager.setUpServerLockFile(FileLockNodeManager.java:108) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.FileLockNodeManager.start(FileLockNodeManager.java:99) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.internalStart(ActiveMQServerImpl.java:644) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.start(ActiveMQServerImpl.java:571) [artemis-server-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.integration.FileBroker.start(FileBroker.java:64) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:127) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:160) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:108) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:135) [artemis-cli-2.22.0.jar:2.22.0]
artemis_1        |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [java.base:]
artemis_1        |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [java.base:]
artemis_1        |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [java.base:]
artemis_1        |      at java.base/java.lang.reflect.Method.invoke(Unknown Source) [java.base:]
artemis_1        |      at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:134) [artemis-boot.jar:2.22.0]
artemis_1        |      at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:50) [artemis-boot.jar:2.22.0]
```

This occur when I next configuration is used

```yaml
volumes:
   - ./data/artemis:/var/lib/artemis-instance/data
```

**Artemis** menu also disappear from the Artemis **Management Console**

![image](https://user-images.githubusercontent.com/56565073/175034095-525ab08e-22e1-4c67-a7bc-d190b3e2e139.png)

**Comment by aspirio187** [comment]
# EDIT

I mistipt the volume from the container to map, however the error is exactly the same and the logs too
